### ISSUE TITLE
TOO MUCH BLOOD

### ISSUE THREAD

**Issue by EmoGarbage404** [frigid14/stationware#105]
## Description

all of the gibbing absolutely covers the map in blood.
this isn't awful, but it really just sucks to look at and really kills the vibe.
similarly, all of the body parts/organs should be cleaned up as well.

**Comment by Just-a-Unity-Dev** [comment]
ert janitor :godo: seriously tho, it wouldn't hurt to put drains under the walls (or make walls function as drains)

**Comment by EmoGarbage404** [comment]
i think the blood prototype should just be changed to evaporate in about a second.

**Comment by Just-a-Unity-Dev** [comment]
sgtm
