### ISSUE TITLE
Implement basic StationWare: Extended gamemode

### ISSUE THREAD

**Issue by EmoGarbage404** [frigid14/stationware#11]
## Description

This is for a more chill and low-stress environment.
- run events as normal
- when a player dies, respawn them at the next ware event
- player should lose all of their belongings

this is kinda unbalanced but with the automatic shuttle call it should be fine.
probably introduce a base-case where if everyone dies in a single round, the game ends.

**Comment by Just-a-Unity-Dev** [comment]
Closing in favor of challenge-style warioware
