### ISSUE TITLE
Need server branding

### ISSUE THREAD

**Issue by EmoGarbage404** [frigid14/stationware#5]
## Description

ideally we don't want to look like stock ss14.

**Comment by Just-a-Unity-Dev** [comment]
a quick logo i drafted

![image](https://user-images.githubusercontent.com/67359748/219843282-c516300d-949d-47ad-b409-98bc0eacf9a5.png)

**Comment by EmoGarbage404** [comment]
probably remove the angle of the logo and just make it flat. also maybe reduce color count?

**Comment by Just-a-Unity-Dev** [comment]
i'll pr a logo
